# Ensure battery charge limit sysfs interface is writable without root prompt
z /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1c/APP0001:00/battery_charge_limit 0666 root wheel -
z /sys/class/power_supply/BAT*/charge_control_end_threshold 0666 root wheel -
